=== bashnesnos/grepp-server/grails-app/conf/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.smltools.org/config"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.smltools.org/config">

	<complexType name="root">
		<sequence>
			<element ref="tns:global" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:options" maxOccurs="1" minOccurs="1"></element>
			<element ref="tns:pp_config" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:automation" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:date_time_config" maxOccurs="1" minOccurs="0">
			</element>
			<element ref="tns:custom" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>


	<complexType name="global">
		<sequence>
            <element ref="tns:params_factory" maxOccurs="1" minOccurs="1"></element>
            <element ref="tns:spooling" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:results_dir" maxOccurs="1"
				minOccurs="0">
			</element>
			<element ref="tns:default_options" maxOccurs="1"
				minOccurs="0">
			</element>

		</sequence>
	</complexType>

	<complexType name="options">
		<sequence>
			<element ref="tns:opt" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="option">
		<simpleContent>
			<extension base="string">
				<attribute name="handler" type="string"></attribute>
				<attribute name="field" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="pp_config">
		<sequence>
			<element ref="tns:pp_splitter_types" maxOccurs="unbounded"
				minOccurs="1">
			</element>
			<element ref="tns:pp_separators"></element>
		</sequence>
		<attribute name="default_sep" type="string"></attribute>
	</complexType>

	<complexType name="pp_splitter_types">
		<sequence>
			<element ref="tns:splitter_type" maxOccurs="unbounded"
				minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="splitter_type">
		<attribute name="handler" type="string"></attribute>
		<attribute name="handler_type" type="string"></attribute>
		<attribute name="id" type="string"></attribute>
	</complexType>

	<complexType name="pp_separators">
		<sequence>
			<element ref="tns:separator" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>


	<complexType name="separator">
		<simpleContent>
			<extension base="string">
				<attribute name="id" type="string"></attribute>
				<attribute name="spool" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="automation">
		<sequence>
			<element ref="tns:level" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="level">
		<attribute name="handler" type="string"></attribute>
		<attribute name="id" type="string"></attribute>
		<attribute name="order" type="int"></attribute>
		<attribute name="fireonce" type="string"></attribute>
		<attribute name="tags" type="string"></attribute>
	</complexType>

	<complexType name="date_time_config">
		<sequence>
			<element ref="tns:pattern" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="pattern" mixed="true">
		<simpleContent>
			<extension base="string">
				<attribute name="tags" type="string"></attribute>
				<attribute name="alevel" type="string"></attribute>
				<attribute name="id" type="string"></attribute>
				<attribute name="order" type="int"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<element name="spooling" type="string"></element>

	<element name="default_options" type="string"></element>

	<element name="opt" type="tns:option"></element>

	<element name="splitter_type" type="tns:splitter_type"></element>

	<element name="pp_splitter_types" type="tns:pp_splitter_types"></element>

	<element name="separator" type="tns:separator"></element>

	<element name="pp_separators" type="tns:pp_separators"></element>

	<element name="pp_config" type="tns:pp_config"></element>

	<element name="options" type="tns:options"></element>

	<element name="level" type="tns:level"></element>

	<element name="automation" type="tns:automation"></element>

	<element name="pattern" type="tns:pattern"></element>

	<element name="date_time_config" type="tns:date_time_config"></element>

	<complexType name="custom">
		<sequence>
			<element ref="tns:options" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:config" maxOccurs="unbounded" minOccurs="0">
			</element>
			<element ref="tns:thread_configs" maxOccurs="1" minOccurs="0">
			</element>
			<element ref="tns:pp_splitters" maxOccurs="1" minOccurs="0">
			</element>
			<element ref="tns:filters" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="config">
		<sequence>
			<element ref="tns:date_format" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:date" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:starter" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:log_threshold" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:pattern" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="id" type="string"></attribute>
	</complexType>

	<element name="date_format" type="string"></element>

	<element name="starter" type="string"></element>

	<element name="date" type="string"></element>

	<element name="log_threshold" type="string"></element>

	<element name="config" type="tns:config"></element>

	<complexType name="thread_configs">
		<sequence>
			<element ref="tns:extractors" maxOccurs="1" minOccurs="1"></element>
			<element ref="tns:skipends" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:ends" maxOccurs="1" minOccurs="1"></element>
		</sequence>
		<attribute name="alevel" type="string"></attribute>
	</complexType>



	<complexType name="thread_patterns">
		<sequence>
			<element ref="tns:pattern" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<element name="extractors" type="tns:thread_patterns"></element>

	<element name="skipends" type="tns:thread_patterns"></element>

	<element name="ends" type="tns:thread_patterns"></element>

	<element name="thread_configs" type="tns:thread_configs"></element>

	<complexType name="pp_splitters">
		<sequence>
			<element ref="tns:splitter" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="splitter">
		<simpleContent>
			<extension base="tns:pattern">
				<attribute name="col_name" type="string"></attribute>
				<attribute name="type" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<element name="splitter" type="tns:splitter"></element>

	<element name="pp_splitters" type="tns:pp_splitters"></element>

	<complexType name="filters">
		<sequence>
			<element ref="tns:filter" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>


	<element name="filter" type="tns:pattern"></element>

	<element name="filters" type="tns:filters"></element>

	<element name="custom" type="tns:custom"></element>

	<element name="global" type="tns:global"></element>

	<element name="root" type="tns:root"></element>

    <element name="results_dir" type="string"></element>

    <element name="params_factory" type="string"></element>
</schema>

=== bashnesnos/grepp-server/grails-app/conf/config.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.smltools.org/config"
	xsi:schemaLocation="http://www.smltools.org/config config.xsd">
	<global>
		<params_factory>org.smltools.grepp.config.PredictingParamsHolderFactory</params_factory>
		<spooling>.log</spooling>
		<results_dir>results</results_dir>
		<default_options>-c</default_options>
	</global>
	<options>
		<opt field="VERBOSE" handler="enforceInfo">v</opt>
		<opt field="TRACE" handler="enforceTrace">t</opt>
		<opt field="HELP" handler="printHelp">?</opt>
		<opt field="SPOOLING">s</opt>
		<opt field="FILE_MERGING">m</opt>
		<opt field="USER_ENTRY_PATTERN" handler="setUserLEPattern">L</opt>
		<opt field="PARSE_PROPERTIES" handler="setPropertiesParsing">parse</opt>
		<opt field="ATMTN_LEVEL" handler="setAutomation">c</opt>
		<opt field="ATMTN_LEVEL" handler="setAutomation">a</opt>
		<opt field="ATMTN_LEVEL" handler="setAutomation">f</opt>
		<opt field="ATMTN_LEVEL" handler="setAutomation">e</opt>
		<opt field="DATE_TIME_FILTER" handler="setDateTimeFilter">dtime</opt>
	</options>
	<pp_config default_sep="csv">
		<pp_splitter_types>
			<splitter_type handler="processPostFilter" id="filter" />
			<splitter_type handler="processPostCounter" id="counter" />
			<splitter_type handler="processPostGroup" id="group" />
			<splitter_type handler="processPostAverage" id="avg"
				handler_type="group_method" />
		</pp_splitter_types>
		<pp_separators>
			<separator id="csv" spool=".csv">,</separator>
		</pp_separators>
	</pp_config>
	<automation>
		<level handler="parseCustomConfig" id="entry_pattern" order="1"
			tags="c, e, a" />
		<level handler="parseFilterConfig" id="filter_pattern" order="2"
			fireonce="true" tags="f, a" />
		<level handler="parseExecuteThreadConfig" id="execute_thread"
			order="3" tags="e, a" />
		<level handler="parsePostFilterConfig" id="post_process_pattern"
			order="4" fireonce="true" tags="f, a" />
	</automation>
	<date_time_config>
		<pattern id="INPUT_DATE_TIME_FORMAT" order="1" tags="dtime">yyyy-MM-dd'T'HH:mm:ss</pattern>
		<pattern id="INPUT_DATE_TIME_FORMAT_M" order="2" tags="dtime">yyyy-MM-dd'T'HH:mm</pattern>
		<pattern id="INPUT_DATE_TIME_FORMAT_H" order="3" tags="dtime">yyyy-MM-dd'T'HH</pattern>
		<pattern id="INPUT_DATE_TIME_FORMAT_D" order="4" tags="dtime">yyyy-MM-dd</pattern>
		<pattern id="INPUT_DATE_TIME_FORMAT_m" order="5" tags="dtime">yyyy-MM</pattern>
		<pattern id="INPUT_DATE_TIME_FORMAT_Y" order="6" tags="dtime">yyyy</pattern>
	</date_time_config>
	<custom>
		<config id="properties">
			<starter>log4j.logger</starter>
			<pattern>log4j\.properties</pattern>
		</config>
	</custom>
</root>
